spring:
  profiles:
    active: local

  datasource:
    url: jdbc:h2:tcp://localhost/~/bookmanager
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        defaul_batch_fetch_size: 1000

  messages:
    basename: messages,errors
    encoding: UTF-8

  data:
    web:
      pageable:
        default-page-size: 10
        one-indexed-parameters: false

server:
  port: 9000

logging:
  level:
    org.hibernate.SQL: debug
